version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}

  sensorapi:
    image: ${DOCKER_REPO}/sensors-api:0.0.1
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - REDIS_HOST=redis
